import {
  loadTrasladosCount,
  countTraslados,
  addTraslado,
  loadTrasladoById,
  loadTrasladoItem,
  updateTrasladoAction,
  updateCodInterno,
  getTrasladoByIdAction,
  saveTrasladoEntregaLocal,
  countTrasladosLocal,
  updateTrasladoActionLocal,
  removeTrasladoActionLocal,
  updateTrasladoRecepcionAction,
  countTrasladosLocalResult,
} from "./traslados-actions";
import trasladosReducer from "./traslados-reducer";
export {
  loadTrasladosCount,
  trasladosReducer,
  countTraslados,
  addTraslado,
  saveTrasladoEntregaLocal,
  loadTrasladoById,
  loadTrasladoItem,
  updateTrasladoAction,
  updateCodInterno,
  getTrasladoByIdAction,
  countTrasladosLocal,
  updateTrasladoActionLocal,
  removeTrasladoActionLocal,
  updateTrasladoRecepcionAction,
  countTrasladosLocalResult,
};
